[tools]
neovim = "latest"
node = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:devcontainer" = "latest"
prettier = "latest"
ruby = "3.4"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node", "python"]
