[tools]
neovim = "0.11.2"
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:devcontainer" = "latest"
ruby = "3.4"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
